### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by theresasogunle** [assuncaocharles/react-indexed-db#12]
When running initDB(DBConfig) in a test, like Jest. TypeError: Cannot read property 'open' of undefined is displayed

**Comment by assuncaocharles** [comment]
> The reason why our test didn't work is because indexedDB is undefined in the global namespace; IndexedDB is a browser API, so does exist in the global namespace in a browser's window object, but in a Node environment, the global object does not have an IndexedDB.

[Testing your IndexedDB code with Jest](https://dev.to/andyhaskell/testing-your-indexeddb-code-with-jest-2o17)
