### ISSUE TITLE
Bug - exception in private window in Firefox 

### ISSUE THREAD

**Issue by martinboksa** [assuncaocharles/react-indexed-db#22]
# BUG
Firefox private window throws an error:

`uncaught exception: IndexedDB error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

Please, maybe any a workaround? 

Thanks

**Comment by assuncaocharles** [comment]
Indexed db is not supported in private window: [IndexedDB best practices](https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/indexeddb-best-practices)

**Comment by martinboksa** [comment]
Yes, I know but there is no workaround on how to check it. 

```
 try {
    initDB({
      name: DATABASE_NAME,
      version: DATABASE_VERSION,
      objectStoresMeta: DATABASE_STORE,
    });
  } catch (e) {
    console.log('Never triggered!');
  }
```

So then I could not hide the hook useIndexedDB
```
  const { add, getAll } = useIndexedDB(TABLE_PUBLICATION_READ);
```

Maybe add 'on error' response? Or any tips to fix?
