### ISSUE TITLE
Initialize the indexdb with data in bulk mode ?

### ISSUE THREAD

**Issue by malick-it** [assuncaocharles/react-indexed-db#26]
Hello

Need to know if there is a way to bulk insert data in the indexdb.

Thank you

**Comment by assuncaocharles** [comment]
Can you be more descriptive in what you wanna do?

**Comment by malick-it** [comment]
> Can you be more descriptive in what you wanna do?

The question is about how to insert multiple documents in the database without iterating upon each item. Pouchdb give this sort of functionnality. 
Thanks.

**Comment by assuncaocharles** [comment]
I understand what the question is about, we don't have the feature, if you can provide some code example what you are trying to do I can help you to find some way to do it otherwise to think about adding new feature :)
