### ISSUE TITLE
db.add breaks the code

### ISSUE THREAD

**Issue by srishti-dev** [assuncaocharles/react-indexed-db#28]
import { useIndexedDB } from 'react-indexed-db';

const { add } = useIndexedDB("locations");
add({location: "new2"}).then(
      (event) => {
        console.log("ID Generated: ", event.target.result);
      },
      (error) => {
        console.log(error);
      }

In event we just get a value as number. I guess  it returns the number of rows in the specific store.
so it breaks event.target ..

**Comment by assuncaocharles** [comment]
Can you provide a small codesandbox repro?

**Comment by assuncaocharles** [comment]
Hi, we are actually returning the new key created for the record, so we are basically returning `event.target.result` so you don't have to catch it by yourself
