### ISSUE TITLE
getAll can't be used in a dependancy array 

### ISSUE THREAD

**Issue by Tbaut** [assuncaocharles/react-indexed-db#29]
Using a pretty simple app, where I'm calling `getAll` in a `useEffect`, and having `getAll` part of the dependencies array, the app keeps re-rendering because `getAll` function is new at each render.

Example:
```ts
const Main = ({ className }: Props) => {
	const [ticks, setTicks] = useState<Tick[]>([]);
	const { getAll } = useIndexedDB(objectStoreName);

	useEffect(() => {
		console.log("boom");
		getAll()
			.then((all) => {
				setTicks(all);
			})
			.catch((e) => console.error(e));
	}, [getAll]);


	return (
		<div>{JSON.stringify(ticks)}</div>
	);
};
```

This code would print "boom" over and over in the console.

I had a look at your code, I would expect to see a `useCallback` wrapping `getAll` to make sure it's re-created only when needed but since you're not using hooks for this I've a hard time pin-pointing where the problem is.

**Comment by seanwash** [comment]
Would it be possible to get a new release on NPM? While I see the above issue has been fixed, the current latest version on NPM reflects an older version of this lib.

**Comment by seanwash** [comment]
Would it be possible to get a new release on NPM? While I see the above issue has been fixed, the current latest version on NPM reflects an older version of this lib.
