### ISSUE TITLE
getById doesn't allow to get by an id string

### ISSUE THREAD

**Issue by jsjexpert** [assuncaocharles/react-indexed-db#34]
indexed-db.ts line 78

Current implementation forces a numeric id during lookup even though we can save non-numeric ones. removing the + resolves it.

Current:
`        const request = store.get(+id);`

Corrected:
`        const request = store.get(id); //removed + to allow for string id lookup`

**Comment by hobblyhoy** [comment]
I ran into this as well. Would love to see it fixed!

**Comment by assuncaocharles** [comment]
@AntonyRafael Will have a look

**Comment by hobblyhoy** [comment]
Awesome, thanks for taking care of that!
