### ISSUE TITLE
please support next.js

### ISSUE THREAD

**Issue by iamdenny** [assuncaocharles/react-indexed-db#42]
![image](https://user-images.githubusercontent.com/1505166/115210492-9cc07b00-a139-11eb-9372-5bc6315db3be.png)

I'm not going to use this in server side.
but I need to import this library. 
please make this work.

**Comment by assuncaocharles** [comment]
Hi  @iamdenny 

Feel free to open a PR fixing it.

**Comment by bhpoliveira** [comment]
Hey @iamdenny do you mind providing a code sample and a bit more context?
Some options are using [dynamic imports ](https://nextjs.org/docs/advanced-features/dynamic-import) and react's [useEffect hook](https://reactjs.org/docs/hooks-effect.html). The last one will prevent the code of run on the server-side.

**Comment by assuncaocharles** [comment]
I can't reason why a indexeddb lib should support server side rendering, can you tell what you are trying to achieve
