### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [assuncaocharles/react-indexed-db#62]
I met this error when I use react18. Is there a plan for update?
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree       
npm ERR! 
npm ERR! While resolving: noname@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from react-indexed-db@1.0.12
npm ERR! node_modules/react-indexed-db
npm ERR!   react-indexed-db@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\SNORLAX\AppData\Local\npm-cache\_logs\2023-06-24T02_18_48_290Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SNORLAX\AppData\Local\npm-cache\_logs\2023-06-24T02_18_48_290Z-debug-0.log
```

**Comment by andythebreaker** [comment]
me too!
don't know why

**Comment by dethstrobe** [comment]
give my fork a shot. https://www.npmjs.com/package/react-indexed-db-hook

```
npm i react-indexed-db-hook
```

I've got it working on [my project](https://github.com/HeyOmae/OMA3) running react 18.2.0

**Comment by S-N-O-R-L-A-X** [comment]
> 

It seems great, but I don't know why the repo link in https://www.npmjs.com/package/react-indexed-db-hook directs to this repo. 😆

**Comment by S-N-O-R-L-A-X** [comment]
> give my fork a shot. https://www.npmjs.com/package/react-indexed-db-hook
> 
> ```
> npm i react-indexed-db-hook
> ```
> 
> I've got it working on [my project](https://github.com/HeyOmae/OMA3) running react 18.2.0

It looks great, but I don't know why the repo link in https://www.npmjs.com/package/react-indexed-db-hook still directs to this repo. 😆

**Comment by dethstrobe** [comment]
That's because I didn't know I needed to update that in the package.json, and when I did I still need to cut a new release. But I don't think it's worth cutting a release just to update that link...but maybe I'm wrong...
